export const BASE_URL = 'http://localhost:3001/api/v1'
export const AUTH = '@AUTH'
export const LOGOUT = '@LOGOUT'
export const SET_USER = '@USER/DATA'
export const CREATE_SURVEY = '@CREATE_SURVEY'
export const INIT_SURVEYS = '@INIT_SURVEYS'
